from typing import TypedDict
from pydantic import BaseModel , Field
class SqlQueryRetrialState(TypedDict):
    user_question : str
    tables_available : list 
    table_details : dict 
    required_tables : list
    query : str 
    verified : bool = False
    retry_no : int = 0 
    last_sql: str
    last_error: str
    confidence : float = 0.0
    last_suggetion : str = ""
    last_issues : list[str] = ""
    final_answer : str = ""
    result : list




class RequiredTables(BaseModel):
    table_name : list[str] = Field(description="List of required table names for the SQL query")

class QueryResult(BaseModel):
    query : str = Field(description="The SQL query generated by the agent")
    confidence : float = Field(description="Confidence score of the generated SQL query")


class CriticResult(BaseModel):
    approved: bool = Field(description="Whether the SQL query is correct and safe to execute.")

    confidence: float = Field(ge=0.0,le=1.0,description="Confidence score between 0.0 and 1.0.")

    issues: list[str] = Field(default_factory=list,description="List of problems found in the SQL query.")

    suggestions: list[str] = Field(default_factory=list,description="Concrete suggestions to fix the issues.")

    summary: str = Field(description="Short overall assessment of the SQL query.")

class FinalAnswer(BaseModel):
    answer: str = Field(description="The final answer to the user's question, based on the SQL query results or other reasoning.")
    