from pydantic import BaseModel , Field
from graph.state import State
from utils.llm import llm
class EvidanceCollection(BaseModel):

    topic : str = Field(description="Topic of the evidance which is collected")

    evidance_list : list[str] = Field(description="All the evidance list which is collected of the topic")



def evidence_collector(state : State) -> State:

    llm_structured_output = llm.with_structured_output(EvidanceCollection)

    reponse = llm_structured_output.invoke(
       f"""You are an Evidence Collection Agent.

            Extract the most important facts from the
            research results.

            Research result : 
            {state['research_results']}

            User query :
            {state['user_query']}


            Rules:
            - Remove duplicates.
            - Keep only factual information.
            - Organize by topic.
            - Return concise bullet points.
            Return in the given Structual formate"""
                )
    return {
        'evidence' : reponse.model_dump()
    }


if __name__ =="__main__":
    response = evidence_collector({'research_results' :
        [{'topic': 'What is the definition and historical origin of the Kannada film industry, also known as Sandalwood?',
  'content': [{'title': 'Kannada cinema - Wikipedia',
    'url': 'https://en.wikipedia.org/wiki/Kannada_cinema',
    'content': "Kannada cinema, also known as Sandalwood, or Chandanavana, is the segment of Indian cinema dedicated to the production of motion pictures in the Kannada language, widely spoken in the state of Karnataka. Kannada cinema is based in Gandhi Nagar, Bengaluru. The 1934 film Sati Sulochana directed by Y. V. Rao was the first talkie film released in the Kannada language. It was also the first film starring Subbaiah Naidu and Tripuramba, and the first screened in the erstwhile Mysore Kingdom. It was produced by Chamanlal Doongaji, who in 1932 founded South India Movietone in Bengaluru. [...] ## History\n\n### Early history\n\nIn 1934, the first Kannada talkie, Sati Sulochana, appeared in theatres, followed by Bhakta Dhruva (aka Dhruva Kumar). Sati Sulochana, starring Subbaiah Naidu and Tripuramba, was shot in Kolhapur at the Chatrapathi studio; most filming, sound recording, and post-production was done in Chennai.\n\nIn 1949, Honnappa Bhagavathar, who had earlier acted in Gubbi Veeranna's films, produced Bhakta Kumbara and starred in the lead role along with Pandaribai. In 1955, Bhagavathar again produced a Kannada film, Mahakavi Kalidasa, in which he introduced actress B. Saroja Devi. B. S. Ranga was an Indian photographer, actor, writer, producer and director made many landmark movies in Kannada, under Vikram Studios.\n\n### Mainstream [...] Kannada cinema is reported to have 8% market share in the gross domestic box office collections for the period January to August 2022, making it the fourth-biggest Indian film industry. The share rose to 9% by October 2022. The total gross collections of the top five Kannada movies of 2022 in first ten months was reported to be ₹1800 crores. The year 2022 began new era for the industry in terms of popularity, quality content and collections. However, the market share of Kannada movies in the gross domestic box office collections declined to 2% in 2023 with the footfalls dropping from 8.1 to 3.2 crores in 2022.\n\n## History\n\n### Early history",
    'score': 0.87681407},
   {'title': 'Kannada cinema Facts for Kids',
    'url': 'https://kids.kiddle.co/Kannada_cinema',
    'content': '## What is Sandalwood?\n\nSandalwood is the popular nickname for the Kannada film industry. It\'s similar to how the Mumbai film industry is called Bollywood. The name "Sandalwood" comes from the rich sandalwood forests found in Karnataka. These forests are famous for their fragrant wood.\n\n### The Beginning of Kannada Cinema\n\nThe very first silent film made in Kannada was Bhakta Dhruva in 1928. However, it was never released. The first talkie (a movie with sound) was Sati Sulochana, released in 1934. This movie was a big step for the industry, bringing sound and dialogue to the screen.\n\n#### Early Stars and Stories [...] |  |\n\n|  |\n\n# Kannada cinema facts for kids\n\nKids Encyclopedia Facts\n\nKannada cinema is the name for movies made in the Indian state of Karnataka. Most of these films are in the Kannada language. Sometimes, movies are also made in Konkani or Tulu languages. This part of the Indian film industry is also known as Sandalwood.\n\n## Contents\n\n What is Sandalwood?\n  + The Beginning of Kannada Cinema\n    - Early Stars and Stories\n Famous Personalities in Sandalwood\n  + Dr. Rajkumar: The Superstar\n  + Vishnuvardhan: The Phoenix\n  + Honnappa Bhagavathar: A Pioneer\n The Growth of Sandalwood\n  + Modern Trends in Kannada Cinema\n Images for kids\n\n## What is Sandalwood? [...] ### Honnappa Bhagavathar: A Pioneer\n\nHonnappa Bhagavathar was an important figure in early Kannada cinema. He was an actor, singer, and producer. He helped establish the industry and was known for his strong voice and acting skills. He contributed a lot to the growth of Kannada films.\n\n## The Growth of Sandalwood\n\nOver the years, Kannada cinema has grown a lot. It has produced many different types of movies, including action, comedy, drama, and romantic films. The industry continues to experiment with new stories and technologies.\n\n### Modern Trends in Kannada Cinema',
    'score': 0.76385427},
   {'title': 'History of kannada cinema - The Quiet Frame - WordPress.com',
    'url': 'https://itsmeadarsh.wordpress.com/tag/history-of-kannada-cinema',
    'content': 'Skip to content\n\n# The Quiet Frame\n\n## Framing reflections on Art, Culture, Literature, Music, Cinema and Travel 🇮🇳🇬🇧\n\n# Tag: History of kannada cinema\n\n# History of Kannada Cinema\n\n10 Comments\n\nIn 1913, India joined the ranks of the first few countries to produce feature films. The first full-length motion picture in India was produced by Dadasaheb Phalke, who is regarded as the pioneer of the Indian film industry. The film industry in Karnataka state referred to as Sandalwood and also known as Chandanavana, is a part of Indian cinema where films are produced in the Kannada language.\n\n##### A QUICK LOOK AT THE GLIMPSE OF 80 YEARS OF KANNADA CINEMA: [...] The 1970s and 1980s are often considered the Golden Age of Kannada cinema. In the 1970s, Dr. Vishnuvardhan and Ambareesh emerged as stars through Puttanna Kanagal’s directorial Naagarahaavu. This period also witnessed the birth of alternate or parallel cinema in Sandalwood. The Kannada film industry was considered a leader of South Indian cinema during this phase. Vishnuvardhan went on to become a superstar of South India, acting in 220 films across five major languages of the country. [...] In 1934, the first Kannada talkie, Sati Sulochana, appeared in theatres, followed by Bhakta Dhruva. Both films were major successes. Gubbi Veeranna is considered the doyen of Kannada cinema during the mid to late 1940s. The rise of Dr. Rajkumar in the early 1950s encouraged the Kannada film industry to produce more historical movies. Bedara Kannappa(1954) was the first Kannada film to run for 365 days in theatres and received a letter of appreciation from the central government.',
    'score': 0.75027883},
   {'title': '[PDF] Critical Analysis on History of Kannada Cinema - ijellh',
    'url': 'https://ijellh.com/wp-content/uploads/2015/09/51.-Dr.-B.P.Mahesh-Chandra-Guru-paper-final.pdf',
    'content': 'of Mysore, Manasagangotri, Karnataka RGNF Research Scholar, Department of Studies in Communication and Journalism, University of Mysore, Manasagangothri, Mysore Introduction Kannada film industry is indeed an extension of Kannada theatre. The early film personalities had been actively involved in Kannada theatre world. Kannada films can be classified broadly into commercial films and new wave films. Most of the Kannada films are commercial films which are meant for entertainment and profit making. The new wave films are less in number but they have enriched the Kannada film industry through qualitative and creative contributions. The early Kannada films were based on folklore. The Kannada film industry has grown remarkably during different stages. Early Kannada Films Gubbi Veeranna laid [...] www.ijellh.com 599 Critical Analysis on History of Kannada Cinema Dr. B. P. Mahesh Chandra Guru Professor, Department of Studies in Communication and Journalism, University of Mysore, Manasagangotri Karnataka India  Dr. M.S.Sapna  M. Prabhudev  Mr. M. Dileep Kumar Abstract Kannada film industry is indeed an extension of Kannada theatre. The early film personalities had been actively involved in Kannada theatre world. The Kannada film industry had to struggle during 1929 – 1934. Early Kannada films had to struggle against western culture. The film theatres were not equipped well to exhibit silent and talkie films to the audience. The Kannada film industry had recovered from certain setbacks after 1941. About 24 films were made in Kannada after independence. In1950s, Kannada film industry [...] and film making opportunities. Several films were made in Madras. Kannada film makers and film stars had to live in Madras for making films without adequate capital resources and other facilities”. The Kannada film industry had to struggle during 1929 – 1934. The active involvement of Kannada theatre personalities, efforts of film makers, involvement of Kannada writers and encouragement by local audience were primarily responsible for the growth of Kannada film industry. Gubbi Veeranna single handedly promoted Kannada theatre and cinema. He constructed film theatres in Bangalore, Tumkur and Tiptur for exhibition of Kannada films. He also encouraged G.V.Iyer, Rajkumar, Balakrishna, Narasimharaj, B.V.Karanth and many other talented actors. B.V.Karanth had received professional training in',
    'score': 0.59344494},
   {'title': 'Among the South Films, Why is Sandalwood (Kannada Film Industry) the less known ? : r/IndianCinemaRegional',
    'url': 'https://www.reddit.com/r/IndianCinemaRegional/comments/1mg6uwp/among_the_south_films_why_is_sandalwood_kannada',
    'content': "Reply  Share \n\n[deleted]\n\n•1y ago 1y ago\n\nSandalwood gained prominence in last few years. Piravi was break through movie for Malyalam in 1989. The industry slowly built reputation via Mohanlal and Mamotty gaining fans across states. Tamil is one of oldest movie industry. It also has history with Bollywood as it produced many movies and gave female stars. Mani ratam kept flame burning and Sun TV helped. Telugu gained prominence thanks to RGV in 90's and slowly built base by dubbing and showcasing movies on cable. Compared to other 3 Sandalwood is relatively new kid in market though many know movies like U-Turn, Sapta Sagaradaache Ello - Side A, my personal fav Avane Srimannarayana\n\n Reply  Share \n\n# People also ask about section\n\n People also ask about \n\nBest Kannada movies of all time [...] Sandalwoods big films tend to do the same as tollywood except smaller , people are just more likely to go for tollywood when they want simple masala, this doesn't mean there aren't any good movies from there . Sapta saagaradache ello is a great example of this.\n\n Reply  Share \n\n and Pushpa (Tollywood) , both the movies are larger than Life , Massy Masala Movies with a lot of action, and a story of how a person goes from zero to success in a business world. In KGF it's Gold empire while in Pushpa it's the Red Sandalwood.\n\nBut at the same time I feel like Sandalwood has a lot of Potential to have its own unique Identity like how other film Industries have (specially after watching Lucia).\n\n Reply  Share \n\nImage 6: u/zero_zeppelii_0 avatar\n\nzero_zeppelii_0\n\n•1y ago 1y ago [...] # Among the South Films, Why is Sandalwood (Kannada Film Industry) the less known ? : r/IndianCinemaRegional\nSkip to main contentAmong the South Films, Why is Sandalwood (Kannada Film Industry) the less known ? : r/IndianCinemaRegional\n\nOpen menu Open navigation the less known ?\n\nDiscuss\n\nHey everyone, this is a follow-up post!\n\nHere’s a link to my previous post about the Sandalwood (Kannada) film industry: \n\nLately, I’ve been watching some Kannada films like KGF Chapter 1 & 2, Lucia, and Kantara. While watching them, a question came to mind:\n\nWhy is the Kannada film industry (Sandalwood) relatively lesser-known or discussed online compared to other South Indian industries?",
    'score': 0.5035894}],
  'priority': 'HIGH'},
 {'topic': 'What are the core cultural, linguistic, and thematic concepts that define Kannada cinema?',
  'content': [{'title': '[PDF] issn:2277-7881; impact factor :8.017(2024); ic value:5.16 - Amazon S3',
    'url': 'http://s3-ap-southeast-1.amazonaws.com/ijmer/pdf/volume13/volume13-issue1(1)/21.pdf',
    'content': 'films. Despite facing challenges like competition from other regional cinemas and piracy, Kannada cinema continues to thrive, largely due to innovative storytelling and the strategic use of digital platforms. This paper not only highlights key milestones and influential figures but also suggests avenues for future research, such as analyzing economic impacts and exploring cross-regional influences. By examining these aspects, the paper underscores Kannada cinema\'s vital role in preserving linguistic and cultural identity while contributing to the global cinematic landscape. Keywords: Kannada Cinema, Film revolution, Regional cinema, Heritage, Karnataka Introduction Kannada cinema, also known as Sandalwood, constitutes a significant segment of Indian cinema, with a rich history that [...] and "U-Turn" (2016) represent the contemporary phase where digital technology and global narratives are prominently featured. These milestones indicate the adaptability and resilience of Kannada cinema as it continues to evolve with changing times and audience preferences. Evolution of Film Genres and Themes Traditional and Mythological Themes In its nascent stages, Kannada cinema predominantly sought inspiration from age-old cultural and religious narratives. Early films such as "Sati Sulochana" (1934) and "Bhakta Dhruva" (1934) exemplified this era, with their stories rooted in Hindu mythology and folklore, reflecting the cultural ethos of Karnataka (Raghavendra, 2009). The filmmakers’ emphasis on visual storytelling and rich dramatizations helped these films resonate with regional [...] Kannada cinema thus continues to evolve as a vital tool for social reflection, bridging the gap between entertainment and societal discourse (Kulkarni, 2021). Preservation of Language and Identity Kannada cinema has played a crucial role in preserving and promoting the Kannada language and cultural identity. Through its films, the industry has been instrumental in instilling regional pride and sustaining linguistic heritage, especially in a multilingual country like India. By using Kannada as the primary medium of storytelling, filmmakers have helped to ensure that the language remains vibrant and relevant in the face of globalization and cultural homogenization (Shankar, 2018). The use of localized dialogues, cultural references, and traditional music in films has reinforced a sense of',
    'score': 0.666736},
   {'title': '[PDF] Desi Culture of Kannada Cinema - IJFMR',
    'url': 'https://www.ijfmr.com/papers/2024/4/24157.pdf',
    'content': "in one go. Empowering stories, earthy stories, realistic, historical suspense thriller stories are keeping viewers interested. The habit of viewers to watch at home instead of going to the cinema is increasing. Looking at the background of these factors, it can be observed that the viewers of movies that carry the concept of desi culture are mostly finding it difficult in today's times. If Kannada cinema is to discuss the concept of desi culture, it has to start with the word country. Deshi can be said in a general sense as the unique things related to different regions of a country, but if we look at the traditional concept of country, it is applied to language, literature, dance, and other cultural bases. Both Desi and Desi are derived from the word Deshya. Both these terms are used [...] Desi culture in the seen Kannada movies. All aspects of the concept of ``Desi culture'' should be reflected in our movies. Accordingly, the ``multifaceted'' culture of Kannada country and the country of India is called ``desi culture'' in a broad sense here, as well as Indian culture, Kannada culture, unique culture, regional culture, local culture, etc., are applied to the concept of ``desi culture'' and sometimes they feel like they complement each other. Cultural aspects can also be seen as the elements are laid out. Historically speaking, Kannada cinema has seen a lot of changes and developments from time to time. Similarly, it can be said that the concept of ``Desi Culture'' has acquired various dimensions from time to time in cultural thought. It is also true that we have progressed [...] we take South India itself, there are countless films made in languages like Kannada, Tulu, Malayalam, Tamil, Telugu etc. If we look at the history of Kannada cinema, most of the early films were inspired by folk tales; It is clear from this that we have been trying to adapt the elements of our country culture to the cinema medium since the beginning. Kannada cinema and sensibility of desi communities: In terms of expression and communication, our movies have traveled on two shores, mass and class. Theory matters when it comes to mass. Mass target movies have a target to reach masses while class target movies target a specific class. Both these types of objectives should be combined. The former belongs to the line of commercial films while the latter is related to artistic films. Here we",
    'score': 0.66203266},
   {'title': 'Kannada cinema - Wikipedia',
    'url': 'https://en.wikipedia.org/wiki/Kannada_cinema',
    'content': 'Kannada cinema, also known as Sandalwood, or Chandanavana, is the segment of Indian cinema dedicated to the production of motion pictures in the Kannada language, widely spoken in the state of Karnataka. Kannada cinema is based in Gandhi Nagar, Bengaluru. The 1934 film Sati Sulochana directed by Y. V. Rao was the first talkie film released in the Kannada language. It was also the first film starring Subbaiah Naidu and Tripuramba, and the first screened in the erstwhile Mysore Kingdom. It was produced by Chamanlal Doongaji, who in 1932 founded South India Movietone in Bengaluru. [...] Kannada cinema is known for producing experimental works such as Girish Kasaravalli\'s Ghatashraddha (1977), which won the Ducats Award at the Manneham Film Festival Germany, Dweepa (2002), which won Best Film at Moscow International Film Festival, Singeetam Srinivasa Rao\'s silent film Pushpaka Vimana "Pushpaka Vimana (1987 film)") (1987), Ram Gopal Varma\'s docudrama Killing Veerappan (2016), Prashanth Neel\'s action franchise K. G. F. film series "K.G.F (film series)") being the highest-grossing Kannada film, and Rishab Shetty\'s Kantara "Kantara (film)") (2022). [...] Kannada   + Byari   + Kodava   + Konkani   + Kurumba   + Sholaga   + Tulu   + Urali |',
    'score': 0.657033},
   {'title': '[PDF] A Historical Analysis of Themes and Trends in Kannada Cinema',
    'url': 'https://www.ijar.org.in/stuff/issues/v11-i3/v11-i3-a009.pdf',
    'content': "the industry's themes and trends, revealing its ability to adapt and remain relevant in a constantly changing world. Keywords: Kannada cinema, Historical analysis, Film industry, Themes and trends, Karnataka, Mythology, History, Cultural heritage, Puttanna Kanagal, G. V. Iyer, Commercial cinema Parallel cinema, Technological advancements, Globalization, Audience preferences Black-and-white classics, Contemporary cinema. Introduction: The evolution of Kannada cinema is a captivating narrative that reflects the dynamic cultural and artistic heritage of Karnataka, a southern state in India. This historical analysis delves into the multifaceted journey of Kannada cinema, offering insights into the themes and trends that have sculpted its identity over the decades. Kannada cinema, born in the [...] development of one of India's most vibrant regional film industries. This historical analysis delves into the themes and trends that have shaped Kannada cinema over the years, shedding light on its transformation from its inception to its contemporary status. Kannada cinema, which emerged in the 1930s, initially drew inspiration from mythological and historical narratives, reflecting the socio-cultural fabric of Karnataka. Over the decades, it evolved to encompass a wide range of genres, including romance, drama, comedy, and social issues. The emergence of iconic directors like PuttannaKanagal and G. V. Iyer in the 1960s and 1970s introduced a new wave of storytelling that challenged traditional norms and brought a deeper artistic sensibility to the industry. The 1980s and 1990s witnessed [...] were marked by a deep connection to mythology and history, representing a reflection of Karnataka's rich cultural heritage. As the decades progressed, the industry saw a remarkable period of innovation during the 1960s and 1970s, spearheaded by visionary directors like Puttanna Kanagal and G. V. Iyer. This era introduced new storytelling techniques, themes, and artistic sensibilities. The diversification of themes and genres within Kannada cinema, from mythological narratives to romance, drama, comedy, and social issues, is another significant outcome. It demonstrates the industry's ability to adapt to changing audience preferences and societal dynamics. Furthermore, the coexistence of commercial and parallel cinema, along with the industry's role in preserving and reflecting the cultural",
    'score': 0.6186197},
   {'title': 'Gems of Kannada Art Cinema',
    'url': 'https://wolfcrow.com/gems-of-kannada-art-cinema',
    'content': 'Skip to content\n\nwolfcrow\n\n# Gems of Kannada Art Cinema\n\n10 of the best Kannada Art Cinema, the industry should be proud of.\n\nIndia is a diverse country. It cannot be defined by a singular commonality running throughout the region. You go from North to South and you will be surprised to see the variety that this place has to offer in terms of culture, language, geography, literature and other vitals that define a place. Similar, if you go across from the East to the West. Each place has its own distinct flavor.\n\nSame can be said for Indian Cinema. The problem that has arisen with Indian Cinema and its image internationally is that it is thought to be synonymous with Bollywood, or the Hindi film industry based in Mumbai. [...] The vast differences in the social and cultural milieu of the common Indian person gives rise to a similarly varied bank of stories and experiences. Also, the history of India informs us that it has always mingled with foreign cultures and that intermingling at the grassroot level has given birth of completely unique and hybrid forms of art and literature.\n\nIt has stories concerning the nitty-gritties of the most aristocratic families to the everyday struggles of the poorest individual.\n\nEven the linguistic differences that are present here are so vast that there are entire industries running parallelly, making movies after movies day in and day out. Films are one of the most common mediums of mass entertainment in the country and they are loved by people of every region. [...] Thus, there are many industries running here on the basis of language and culture who make films concerning their own specific issues and also issues which are pan-Indian.\n\nSome of the major industries based on language and region are as follows – Hindi (Parts of North and Central India), Gujarati (Gujarat), Marathi (Maharashtra), Malayalam (Kerala), Tamil (Tamil Nadu), Telugu (Andhra Pradesh and Telangana), Kannada (Karnataka) and Bengali (West Bengal) among others.\n\nTo know more about the Indian Films which made a mark at international film festivals, do check this article out –\n\n> The Top 25 Internationally Acclaimed Indian Films\n\nCopy and paste this code into your site to embed',
    'score': 0.41094592}],
  'priority': 'HIGH'},
 {'topic': 'How does Kannada cinema compare to other major Indian film industries like Bollywood, Tollywood, and Kollywood in terms of scale and regional focus?',
  'content': [{'title': 'MovieMe study reveals regional films’ impact on Indian cinema – Indian Television Dot Com',
    'url': 'https://indiantelevision.com/news-headline/movieme-study-reveals-regional-films-impact-on-indian-cinema',
    'content': 'Hindi cinema, often regarded as mainstream, continues to dominate national box offices, but regional industries like Kannada and Telugu are catching up with high-grossing films like KGF 2, RRR, and Kalki 2898 AD. Certain genre preferences also stood out from these movies, with action flicks and family dramas dominant across most industries.\n\nMovieMe’s data shows that Indian regional cinema is thriving, transcending linguistic barriers and appealing to diverse audiences across the country. Especially in Tamil and Kannada industries with increasing competition amongst titles to capture attention at the box office, regional movies are set to get a growing share of the market in the coming years. [...] The study by MovieMe reflects that, despite the significant average budget and average BO earning differences, each industry is contributing significantly to the Indian cinematic experience, delivering a variety of content that caters to both local and national audiences. For instance, while Malayalam and Kannada cinema appear to deliver compelling narratives at relatively lower budgets, Telugu and Tamil films appear to be bigger-budget blockbusters that garner massive box office success across India. [...] Indian Television Dot Com\n\nConnect with us\n\n### Box Populi\n\n# MovieMe study reveals regional films’ impact on Indian cinema\n\nPublished\n\n2 years ago\n\non\n\nBy\n\nindiantelevision.com Team\n\nMumbai: India’s regional cinema landscape is vast and diverse, with each industry offering unique narratives, cultural contexts, and filmmaking styles. To better understand regional cinema success and growth, MovieMe- a cutting-edge entertainment tech and content discovery platform did a detailed study where they compared five key regional film industries—Malayalam, Kannada, Tamil, Telugu, and Hindi—and their 10 most popular releases post-COVID (2020-2024). MovieMe looked at film budgets, box office (BO) earnings, and genres to get a sense of what makes each regional cinema industry in India unique.',
    'score': 0.6829338},
   {'title': 'Beyond Bollywood: Why Regional Indian Cinema Rules the World',
    'url': 'https://www.aiocine.com/blog/beyond-bollywood-regional-indian-cinema-global-rise',
    'content': "## Kannada Cinema: From Cult to Culture to Crore\n\nRishab Shetty's Kantara (2022) was made for approximately 16 crore. It grossed over 410 crore worldwide. International audiences encountered something they had never seen before.\n\nKantara established a principle now reshaping filmmaking across India: the more deeply specific you go, the more widely resonant you become. You do not dilute your culture for a broader audience. You trust that your culture, fully expressed, is the story.\n\n## Bengali and Marathi Cinema: The Prestige Engines\n\nBengali cinema carries the weight and blessing of the Satyajit Ray legacy. Bengali OTT content — particularly crime and thriller genres — is building a national audience. [...] Manjummel Boys (2024) was made on a budget of approximately 8 crore. It went on to gross over 241 crore worldwide, becoming the highest-grossing Malayalam film in history. It had no major stars. It succeeded entirely on the power of its script and emotional authenticity.\n\nThis is the Malayalam model: story over star, authenticity over spectacle. Films like Aavesham, Premalu, and Kishkindha Kaandam found pan-India audiences who had never previously engaged with Malayalam content.\n\nBut the industry also has to reckon with its internal truth. The Hema Committee report exposed systemic abuse and coercive power dynamics. Real credibility means holding yourself accountable.\n\n## Kannada Cinema: From Cult to Culture to Crore [...] This is not a fluke. This is a tectonic shift that the global film industry is only now beginning to fully understand. Regional Indian cinema — Telugu, Tamil, Malayalam, Kannada, Bengali, Marathi — has quietly, ferociously become the most exciting film ecosystem on the planet.\n\n## The Numbers Don't Lie: A Box Office Revolution\n\nAccording to Variety's 2025 Indian box office report, the Telugu film industry alone commanded a 20% share of India's total domestic box office gross in 2024, generating approximately $272.6 million. Tamil cinema held 15% at $212.4 million. Malayalam cinema doubled its market share from 5% to 10% in a single year, crossing $135 million.",
    'score': 0.67501575},
   {'title': 'Bollywood vs South Industry: How Each Industry Navigates Legal Challenges - Music and the Arts - India',
    'url': 'https://www.mondaq.com/india/music-and-the-arts/1735688/bollywood-vs-south-industry-how-each-industry-navigates-legal-challenges',
    'content': 'Biographies and autobiographies (e.g., Sanju, MS Dhoni: The Untold Story)\n International films (official or unofficial remakes)\n Novels or short stories\n\nThe Bollywood industry is star-driven, so content that guarantees box-office appeal or built-in recognition is preferred. Hence, storytelling tends to revolve around urban, contemporary, or celebrity-centric narratives.\n\nOn the other hand, the South Industry (i.e. Telugu/Tamil/Kannada/Malayalam) focuses on original stories with hero-centric, culturally rooted narratives prioritizing on:\n\n Mass-appeal action spectacles (Baahubali, KGF);\n Folk or mythological tales adapted for modern audiences (RRR, Ponniyin Selvan) and Everyday stories and social dramas—especially in Malayalam cinema (Drishyam, Kumbalangi Nights). [...] So just to summarize:\n\n| Aspect | Bollywood | South Industry (Telugu/Tamil/Kannada/Malayalam) |\n --- \n| Story Focus | Romance, family drama, social themes | Hero-centric, action, folklore, realistic/nuanced storytelling |\n| Action | Moderate, realistic | Larger-than-life, stylized, experimental |\n| Music & Dance | Narrative-driven, glamour | Mood/action-driven, integrates heroism & spectacle |\n| Language & Culture | Hindi, urban pan-India | Regional languages, strong local cultural flavor |\n| Innovation | Gradual, risk-averse | Bold, experimental often trend-setting |\n\nBoth industries influence each other—recent years have seen South Indian blockbusters remade in Hindi and Bollywood experimenting with South-style action and visuals.',
    'score': 0.6296157},
   {'title': 'Cinema of India - Wikipedia',
    'url': 'https://en.wikipedia.org/wiki/Cinema_of_India',
    'content': '### Kannada\n\n[edit]\n\nMain article: Kannada cinema\n\nKannada cinema, also known as Sandalwood or Chandanavana,( is the segment of Indian cinema( dedicated to the production of motion pictures in the Kannada language, which is widely spoken in Karnataka state.( Sulochana_ (1934, Y. V. Rao) was the first talkie film in the Kannada language.( Kannada films include adaptations of major literary works( and experimental films.(\n\nImage 31\n\nRajkumar on a 2009 postage stamp\n\nImage 32\n\nDirector Girish Kasaravalli (right)\n\n### Kokborok\n\n[edit]\n\nMain article: Kokborok Cinema [...] The Hindi language film industry of Mumbai (formerly Bombay), also known as Bollywood,( is the largest and most powerful branch of Hindi cinema.( Hindi cinema explores issues of caste and culture in films such as _Achhut Kanya_ (1936) and _Sujata "Sujata (1959 film)")_ (1959).( International visibility came to the industry with Raj Kapoor\'s _Awara_ and later in Shakti Samantha\'s_Aradhana "Aradhana (1969 film)")_.( Art film directors include Kaul, Kumar Shahani, Ketan Mehta, Govind Nihalani, Shyam Benegal,( Nair, Nagesh Kukunoor, Sudhir Mishra and Nandita Das. Hindi cinema grew during the 1990s with the release of as many as 215 films annually. Magazines such as _Filmfare_, _Stardust "Stardust (magazine)")_ and _Cine Blitz_ popularly cover the industry.(\n\n### Kannada\n\n[edit] [...] Sridevi is widely regarded as the first female superstar of Indian cinema due to her pan-Indian appeal with equally successful careers in Hindi, Tamil, Malayalam, Kannada and Telugu cinema. She is the only Bollywood actor to have starred in a top 10 grossing film each year of her active career (1983–1997)._[citation needed_]\n\nIn 2024, regional film industries collectively accounted for around 60 % of India\'s box office share, with Hindi cinema\'s contribution falling to 40 %, reflecting a notable shift in audience preferences toward regional-language films including Malayalam, Tamil, Telugu, and Gujarati cinema(\n\n#### Telugu\n\n[edit]',
    'score': 0.5786631},
   {'title': '[PDF] Kiranjot Atwal - Indian Media Research Paper - Cloudfront.net',
    'url': 'https://dpl6hyzg28thp.cloudfront.net/media/Kiranjot_Atwal_-_Indian_Media_Research_Paper_536qRqM.pdf',
    'content': 'ody-of-kannada-cinema-industry-has-expressed-solidarity-with-the-states-farmers-the-off ice-bearers-and-executive-committee-members-of-kfcc-held-a-protest-in-front-of-their-of fice-on-thursday-evening-to-protest-the-cauvery-river-authoritys-decision-to-release-900 0-cusecs-of-water-to-tamil-nadu-/articleshow/16477404.cms Manaher, S. (2023, April 27). Tollywood vs Bollywood: Meaning and differences. The Content Authority.  Mehta, S. (2017, May 21). Punjabi films have gained nation-wide acceptance. Tellychakkar.com.\n nce-sargun-mehta-170519 INDIAN MEDIA REPRESENTATION 22 OrmaxMedia. (2023, January 27). 10K crore: Return of the box office. Ormax Media Pvt. Ltd.\n The Otherwoods. TV Tropes. (n.d.).\n Overdorf, J. (2013, January 3). Tamil films give Bollywood a run for its money. thestar.com. [...] Tamil films have been screened at international film festivals and have gained appreciation for their artistic and storytelling merits. The success of movies like "Baahubali" and "2.0" has further contributed to the popularity of Kollywood films beyond Tamil-speaking audiences (Reith-Banks, 2019).\nOverall, Kollywood is a dynamic film industry that has made significant contributions to Indian cinema and has its unique identity in the global film landscape.\nSandalwood The Sandalwood film industry, also known as the Kannada film industry, is the regional film industry based in the state of Karnataka in India. It is named after the fragrant sandalwood tree that is native to the region and has played a significant role in the state\'s culture and economy. [...] Moreover, Indian cinema acts as a unifying force, connecting people across different regions, languages, and backgrounds. While Bollywood remains the most prominent film industry, Tollywood, Kollywood, Sandalwood, Mollywood, and Punjwood have all played significant roles in shaping the rich tapestry of Indian cinema. These industries contribute to the diverse representation of Indian culture and offer a platform for regional narratives and artistic expressions.',
    'score': 0.55362654}],
  'priority': 'MEDIUM'},
 {'topic': 'What are the key advantages of Kannada cinema, such as its unique storytelling, focus on Kannada literature, and recent technological advancements?',
  'content': [{'title': '[PDF] KANNADA FILM INDUSTRY LATEST NEWS',
    'url': 'https://campaigns.dmu.edu/scholarship/PUE8Bu/0AD020/kannada-film_industry-latest-news.pdf',
    'content': 'The Kannada film industry is also embracing technological advancements to enhance the cinematic experience. The use of advanced visual effects,',
    'score': 0.62879556},
   {'title': '[PDF] A Historical Analysis of Themes and Trends in Kannada Cinema',
    'url': 'https://www.ijar.org.in/stuff/issues/v11-i3/v11-i3-a009.pdf',
    'content': 'Technological Advancements and Globalization: The literature delves into the impact of technological advancements and globalization on Kannada cinema. It',
    'score': 0.462061},
   {'title': 'Adapting Kannada literature into cinematic stories - Facebook',
    'url': 'https://www.facebook.com/groups/filmbuffs/posts/4583776931646279',
    'content': '“I grew up reading a lot of Kannada literature. I always wondered why these brilliant stories and novels were never adapted cinematically.',
    'score': 0.28657386},
   {'title': 'Adapting novels into films can bring fresh perspectives to Kannada cinema: Gurudatha Ganiga | Kannada Movie News - The Times of India',
    'url': 'https://timesofindia.indiatimes.com/entertainment/kannada/movies/news/adapting-novels-into-films-can-bring-fresh-perspectives-to-kannada-cinema-gurudatha-ganiga/articleshow/113571973.cms',
    'content': "Article image for: 5 Vastu-approved plants you should bring home today for prosperity\nArticle image for: 5 effective ways to keep spiders away from your home and garden (third is a magical remedy!)\nArticle image for: Top 6 cheapest destinations to travel in India in 2026\nArticle image for: 8 types of kadhi from across India to try for lunch\nArticle image for: Scarlett Johansson net worth: Inside the USD 165 million fortune of Marvel’s ‘Black Widow’ star\nArticle image for: From Bad Bunny, Green Day to Charlie Puth: Full list of Super Bowl 60 performers\nArticle image for: From a massive living room to lavish bedrooms: A look at Samay Raina’s luxurious house\nArticle image for: PM Narendra Modi’s Panch Prana goal and the role of Shatavari and it’s importance in traditional Indian kitchens [...] ## Featured In Movies\n\nArticle image for: 'Border 2' crosses Rs 300 crore mark in India\nArticle image for: Salman reacts after Mohan Bhagwat calls him an inspiration\nArticle image for: Stars who rocked the Super Bowl Halftime show from 2020-2025\nArticle image for: Jaideep Ahlawat birthday special: Ranking his most powerful OTT performances\nArticle image for: Sudha Chandran recalls chilling paranormal encounters\nArticle image for: Scarlett Johansson's net worth\nArticle image for: Vinod Khanna was ‘traumatized’ after leaving Osho: Wife\nArticle image for: Amaal and Farrhana unveil first look of 'Yahin Guzaar Doon'\nArticle image for: ‘A Knight of the Seven Kingdoms’ episode 3 prophecy explained\nArticle image for: Celina recalls learning about brother’s detention amid divorce\n\n## [...] Article image for: 7 warning signs of structural defects every homeowner should know\nArticle image for: ‘The Fame Game’, ‘Mrs. Deshpande’, ‘Maa Behen’: Madhuri Dixit Nene’s evolving OTT journey\nArticle image for: 'Very Painful Times': Melinda Gates Opens Up On Bill Gates & Epstein Controversy\nArticle image for: 'Very Painful Times': Melinda Gates Opens Up On Bill Gates & Epstein Controversy\nArticle image for: Savannah Guthrie Begs For Missing Mother’s Safe Return: ‘We Are Ready To Talk’\nArticle image for: D4vd’s Friend Breaks Silence? Neo Langston Appears Before Grand Jury In Celeste Rivas Case\nArticle image for: Andrew 'Booted Out' Of Royal Lodge As Latest Epstein Emails Reveal Harrowing Details",
    'score': 0.28419885},
   {'title': 'What are some Kannada movies based on popular novels and books?',
    'url': 'https://www.quora.com/What-are-some-Kannada-movies-based-on-popular-novels-and-books',
    'content': "1.Besuge (1976 ) , nilukada nakshatra (1995) , kappu kola , mana midiyithu(based on the novel named 'viplava') , kamanabillu (based on novel '",
    'score': 0.16122806}],
  'priority': 'MEDIUM'},
 {'topic': 'What are the primary disadvantages or limitations currently faced by the Kannada film industry, such as budget constraints and market reach?',
  'content': [{'title': '[PDF] An Empirical Study Concerning the Kannada Movies - ijrti',
    'url': 'https://www.ijrti.org/papers/IJRTI2508042.pdf',
    'content': 'and digital media platforms continue to revolutionise how audiences consume films, the importance of effective and efficient movie marketing has become paramount. Capturing audience attention in a highly competitive entertainment © 2025 IJRTI | Volume 10, Issue 8 August 2025 | ISSN: 2456-3315 IJRTI2508042 International Journal for Research Trends and Innovation (www.ijrti.org) a347 landscape demands strategic promotional efforts that can elevate film visibility, stimulate interest, and ultimately boost ticket sales or viewership. Unlike larger national or multinational film industries with access to substantial marketing budgets, Kannada filmmakers often operate within constrained financial resources. These budgetary limitations restrict the scope for paid advertising campaigns, such as [...] as well as informal audience feedback. In essence, for Kannada filmmakers facing marketing budget constraints, doubling down on authentic, community-driven, and social media-based promotion is likely to deliver outsized impact, both in building audience awareness and sustaining cultural relevance. © 2025 IJRTI | Volume 10, Issue 8 August 2025 | ISSN: 2456-3315 IJRTI2508042 International Journal for Research Trends and Innovation (www.ijrti.org) a354 REFERENCES: 1. Casella, G., & Berger, R. L. (2002). Statistical inference (2nd ed.). Duxbury Press. 2. Devore, J. L. (2021). Probability and statistics for engineering and the sciences (10th ed.). Cengage Learning. 3. International Organization for Standardization. (2019). ISO 80000-2:2019: Quantities and units — Part 2: Mathematics.  4. [...] aim to guide filmmakers and marketers in leveraging these cost-effective strategies, thereby improving film promotion outcomes in a resource-constrained environment. LITERATURE REVIEW: Effective film marketing plays a critical role in the commercial success and cultural reach of cinema industries worldwide. However, regional film sectors, such as the Kannada film industry, face unique challenges due to limited promotional budgets and dominant competition from larger markets. This literature review discusses key concepts and prior research related to non-paid advertising methods, their effectiveness © 2025 IJRTI | Volume 10, Issue 8 August 2025 | ISSN: 2456-3315 IJRTI2508042 International Journal for Research Trends and Innovation (www.ijrti.org) a348 in media promotion, audience',
    'score': 0.81204927},
   {'title': '[PDF] Leveraging Digital Platforms for Film Promotion - Impact Factor: 8.699',
    'url': 'https://www.ijirset.com/upload/2025/NCELGTTVG2025/38_Leveraging%20Digital%20Platforms%20for%20Film%20Promotion%20Analyzing%20the%20Impact%20of%20Social%20Media%20and%20OTT%20Advertising%20on%20the%20Success%20of%20Kannada%20Movies.pdf',
    'content': 'the study within the recent, transformative period of media consumption patterns. Statement of the Problem The Kannada film industry, while culturally significant and increasingly embracing digital technologies, continues to face substantial challenges in fully leveraging digital platforms for film promotion. Although social media and over-the-top (OTT) advertising have reshaped marketing strategies in global and Bollywood cinema, their specific impact on regional films particularly Kannada productions remains inadequately explored. Industry stakeholders contend with constraints such as limited marketing budgets, linguistic barriers, and intense competition from larger film markets. Yet, there is a notable lack of empirical evidence on how digital marketing tools can effectively enhance [...] (₹25 crore budget) grossed over ₹95 crore with 70% of its marketing budget allocated to digital channels. ● Traditional-heavy campaigns: ○ Typically deliver 15–20% lower ROI for films targeting younger demographics. ○ Exception: Star-driven productions (e.g., Darshan-led films) continue to benefit from traditional outreach due to established fan bases. Long-Term Value ● Digital: Assets such as trailers, behind-the-scenes content, and interviews remain accessible indefinitely, sustaining engagement over time. ● Traditional: Advertisements have a limited shelf life, with physical displays typically removed within 2–4 weeks. Industry-Specific Challenges Limitations of Digital Marketing ● Oversaturation: Approximately 68% of Kannada films now prioritise digital marketing (FICCI, 2023). ● [...] income. ● Recommendation: Maintain a minimum six-week theatrical exclusivity for premium productions. Competitive Visibility Kannada films compete directly with high-profile Bollywood and Hollywood titles on OTT homepages. IJIRSET © 2025 | An ISO 9001:2008 Certified Journal | 249 ● Solution: Curated categories such as “Kannada Cinema Spotlight” can improve discoverability. ❖ Comparative Analysis of Digital and Traditional Marketing in Kannada Cinema: Cost-Efficiency and ROI Evaluation Introduction to Marketing Expenditure in Kannada Films The Kannada film industry operates with comparatively modest promotional budgets relative to larger national markets such as Bollywood. This financial constraint heightens the need for cost-effective marketing strategies capable of achieving wide',
    'score': 0.7969415},
   {'title': 'Marketing Trends in Kannada Film Industry – Communication Today',
    'url': 'https://communicationtoday.net/2015/06/29/marketing-trends-in-kannada-film-industry',
    'content': '### Conclusion\n\nThe Kannada film industry produces around 150 films a year. But the research reports indicate that for Kannada films there is no market beyond Karnataka and they have to compete on all fronts with other language movies in their own land.The study finds that the absence of a mechanism to market Kannada movies is hindering their reach to a larger audience. It also stresses the critical role marketing plays in expanding the market and exploiting the untapped opportunities. [...] The geographical reach of Kannada movies is limited outside Karnataka, with a few producers exploring certain selected parts of west and northern India, while hardly one or two movies actually get distributed in the international market. Kannada-speaking population is present outside the state as well as in countries such as Australia, the US and pockets of the Middle East. However, these markets are not exploited, like in the case of Tamil and Telugu movies. [...] Non-visibility of Kannada films at the national and international circuit dominated a panel discussion organized at the sixth edition of Bangalore International Film Festival (6BIFFes, held between 26thDecember2013 and2ndJanuary2014). Panelists, including film critic Uma Da Cunha, Fulbright Film Scholar Karen Folger Jacobs, eminent film scholar Aruna Vasudev and film festival adviser Santhanam, attributed lack of adequate promotion for the crisis plaguing the Kannada film industry.Filmmakers, including national award recipient directors Girish Kasarvalli, P. Sheshadri, T.S. Nagabharana, Ramadas Naidu and others, discussed the problems faced in marketing their films and strongly favoured the necessity for a film market as a promotional arm alongside BIFFes.\n\n### Conclusion',
    'score': 0.7474137},
   {'title': '[PDF] Influence of Low Budget Cinemas on Kannada Film Industry - ijrti',
    'url': 'https://ijrti.org/papers/IJRTI2206321.pdf',
    'content': 'last ten years. Seeing as low-budget films can’t cast top stars in the industry, this niche has given many new actors the opportunity to debut and rise in the ranks, bringing a new wave of talent to the forefront of the Sandalwood industry. Additionally, there is a shift in the focus of the films being made. Writers and directors are now creating films that are content and theme-centric, with an emphasis on developing the plot and characters in novel ways. The budget constraints affect the filming locations available for the production. As a result, there have been several films where the entire film shoot was done within a single city, region or even a single location (Eg: Puta 109, haggada Kone, etc). This shift has also gone hand in hand with the tendency towards films inspired by true [...] lack of theatres – particularly when big stars decide to premiere their films, and insufficient funding. While many say that one of the biggest disadvantages of a low-budget film is a lack of decent exposure, many also believe that low-budget films have ushered in a new trend in Kannada cinema in which content has proven to be the most significant factor. 6. ACKNOWLEDGEMENT I would like to express my sincere gratitude to all those who have been instrumental in the presentation of this research. I express my gratitude to the Head of the Department, Dr. Bhargavi Hemmige and the faculty of the Department of Media Studies, Jain University (Deemed-to-be-University) – Center for Management Studies, Bangalore. I am also thankful to my research guide Prof. Santosh S without whose guidance, this [...] expensive budget and gain huge success in the market, the real challenge lies in making ‘successful’ films with a low or limited funding. From the past few years, low budget cinemas have taken a new turn with their brilliant and witty storylines, screenplay, content and cinematography. It all lies in maintaining a perfect balance between the content and a low budget, and how well it is able to stand out amidst countless other films produced. In the same line, pertaining to Kannada Film Industry, many cinemas have been able to deliver luminary performances in the recent decade. From utilizing minimalistic locations and lesser cast to fascinating and compelling content, this Industry is making news in every way possible. Various researches have concluded that filmmaking in Kannada Cinema',
    'score': 0.72254705},
   {'title': 'Kannada film industry: Searching for its roots',
    'url': 'https://www.ormaxmedia.com/insights/stories/kannada-film-industry-searching-for-its-roots.html',
    'content': 'With the lack of a definite cinematic differentiator, and the industry’s tendency to replicate success stories without adding freshness, an original cinema movement is an unrealized idea in the Kannada industry as of today.\n\n3. A multi-lingual market\n\nPotential Kannada hits end up getting limited release (number of screens, multiplex shows, etc.) compared to films of non-Kannada languages releasing on the same day, eventually leading to a smaller first-day collections for Kannada films. In 2023, Telugu films Kushi and Dasara got a much higher first-day box office in Karnataka than Kannada films Sapta Sagaradaache Ello - Side A and Gurudev Hoysala, which starred Rakshit Shetty and Daali Dhananjaya respectively. [...] Kannada4.png\n\nThis issue, in turn, highlights the absence of multiple bankable stars in the Kannada film industry. Currently, the industry is highly dependent on just two superstars, Kicha Sudeep and Yash. Between them, they control 60% of star popularity share (Ormax Stars India Loves) over the last one year in the Kannada market. Even the Malayalam market is less dependent on its top 2 stars at 47% share between Mohanlal and Mammootty, who are established superstars for decades now (read more about them here). [...] Here is our analysis of some important factors that are hampering consistency and growth of Kannada cinema at the box office:\n\n1. Lack of culturally-rooted content',
    'score': 0.683948}],
  'priority': 'MEDIUM'},
 {'topic': 'What are the significant challenges that Kannada cinema is currently struggling to overcome in terms of distribution, global visibility, and competition?',
  'content': [{'title': 'Marketing Trends in Kannada Film Industry – Communication Today',
    'url': 'https://communicationtoday.net/2015/06/29/marketing-trends-in-kannada-film-industry',
    'content': 'The geographical reach of Kannada movies is limited outside Karnataka, with a few producers exploring certain selected parts of west and northern India, while hardly one or two movies actually get distributed in the international market. Kannada-speaking population is present outside the state as well as in countries such as Australia, the US and pockets of the Middle East. However, these markets are not exploited, like in the case of Tamil and Telugu movies. [...] ### Conclusion\n\nThe Kannada film industry produces around 150 films a year. But the research reports indicate that for Kannada films there is no market beyond Karnataka and they have to compete on all fronts with other language movies in their own land.The study finds that the absence of a mechanism to market Kannada movies is hindering their reach to a larger audience. It also stresses the critical role marketing plays in expanding the market and exploiting the untapped opportunities. [...] Non-visibility of Kannada films at the national and international circuit dominated a panel discussion organized at the sixth edition of Bangalore International Film Festival (6BIFFes, held between 26thDecember2013 and2ndJanuary2014). Panelists, including film critic Uma Da Cunha, Fulbright Film Scholar Karen Folger Jacobs, eminent film scholar Aruna Vasudev and film festival adviser Santhanam, attributed lack of adequate promotion for the crisis plaguing the Kannada film industry.Filmmakers, including national award recipient directors Girish Kasarvalli, P. Sheshadri, T.S. Nagabharana, Ramadas Naidu and others, discussed the problems faced in marketing their films and strongly favoured the necessity for a film market as a promotional arm alongside BIFFes.\n\n### Conclusion',
    'score': 0.6139086},
   {'title': 'Kannada Cinema: Pan-India dreams challenge local film industry',
    'url': 'https://www.deccanherald.com/india/karnataka/big-budgets-bigger-losses-is-pan-india-ambition-hurting-kannada-cinema-3932186',
    'content': 'Kannada Film Industry: After the success of KGF and Kantara, many filmmakers chased pan-India spectacles, but rising budgets, weak scripts',
    'score': 0.57236487},
   {'title': "Why Kannada Cinema Is Struggling: A Filmmaker's Observation of a ...",
    'url': 'https://www.reddit.com/r/ChitraLoka/comments/1tivpa0/why_kannada_cinema_is_struggling_a_filmmakers',
    'content': 'Today, OTT platforms hesitate to acquire Kannada films because the industry itself weakened theatrical confidence. Instead of theatrically',
    'score': 0.5122296},
   {'title': 'Unpopular opinion: Kannada industry has zero overseas audience!!',
    'url': 'https://www.reddit.com/r/ChitraLoka/comments/1j798is/unpopular_opinion_kannada_industry_has_zero',
    'content': "KFI has zero to audience going to theatres in foreign countries unless it's a too good to be true of a big film.",
    'score': 0.4928966},
   {'title': 'Why does #Kannada cinema continue to be the overlooked step ...',
    'url': 'https://www.instagram.com/reel/DMKtV8OxBmJ?hl=en',
    'content': "A platform shouldn't have the right to decide which content to onboard and which not, that's the audience's job. Every film, good or bad,",
    'score': 0.37855154}],
  'priority': 'MEDIUM'},
 {'topic': 'What is the future scope of the Kannada film industry, considering the rise of pan-Indian releases and changing audience consumption patterns?',
  'content': [{'title': 'Kannada Film Industry Latest News',
    'url': 'https://ftp.arcchurches.com/sites/mL9B54/604663/Kannada%20Film%20Industry%20Latest%20News.pdf',
    'content': 'but is leveraging its unique cultural identity to carve a niche. Strategic collaborations with national and international filmmakers are also opening new avenues.2. Preservation of Cultural IdentityAmid modernization, the industry is committed to maintaining its cultural roots. Films like "Kantara" and "Gaalipata" exemplify this balancing act of tradition and innovation.3. Distribution and Exhibition ChallengesTheaters, especially in rural areas, face challenges due to the rise of OTT. Industry stakeholders are exploring hybrid release strategies to maximize reach.Future Outlook and Strategic DirectionsThe latest news from the Kannada film industry indicates a promising future driven by: - Continued technological innovation - Emphasis on storytelling that appeals to both regional and [...] films are gaining popularity, reflecting changing audience tastes. Additionally, the rise of OTT platforms like Amazon Prime Video, Netflix, and Disney+ Hotstar has expanded the reach of Kannada films, sometimes even prioritizing digital release strategies over theatrical runs.Emerging Talent and Industry Shifts1. Rise of New Directors and ActorsThe industry is witnessing a new wave of talent pushing creative boundaries: - Rishab Shetty: Beyond directing, he starred in "Kantara," exemplifying multi-talented artists leading the charge. - Shiva Rajkumar and Sudeep: Veteran actors continue to dominate, but new faces like Prajwal Devaraj and Darshan are also making notable impacts. New directors such as Anup Bhandari and Arun Sri have gained recognition for their innovative storytelling [...] Emphasis on storytelling that appeals to both regional and global audiences - Greater emphasis on digital distribution and marketing - Support for new talent and diverse genres Industry experts predict that Kannada cinema will further strengthen its position by embracing global trends while preserving its cultural essence.Conclusion: Sandalwood’s New DawnThe Kannada film industry is at a pivotal juncture. Recent developments underscore a vibrant, dynamic sector capable of producing content that resonates both locally and internationally. As technology adoption accelerates and creative narratives diversify, Sandalwood is poised to make even more significant strides in the global cinematic landscape. The latest news not only reflects the industry’s resilience amid challenges but also',
    'score': 0.7752821},
   {'title': '[PDF] "A Study of the Most Popular Kannada Films and Series on OTT ...',
    'url': 'https://www.jetir.org/papers/JETIR2411578.pdf',
    'content': 'and the specific elements that attract viewers. The scope encompasses data collection from leading OTT platforms featuring Kannada content, audience feedback through reviews and ratings, and in-depth interviews with industry professionals. The study also explores the role of linguistic and regional identity in the success of these films and series, as well as the impact of emerging technologies like AI in recommending and promoting content. The research is limited to Kannada-language content released or gaining popularity between 2020 and 2024 to ensure relevance to contemporary viewing trends. It targets both domestic and international audiences to capture the broader appeal of Kannada cinema in the digital era. This study’s findings will provide valuable insights for filmmakers, OTT [...] and viewership of Kannada films and series (Bhat & Joshi, 2021). © 2024 JETIR November 2024, Volume 11, Issue 11 www.jetir.org (ISSN-2349-5162) JETIR2411578 Journal of Emerging Technologies and Innovative Research (JETIR) www.jetir.org f674 9. Challenges and Future of Kannada OTT Content A study by Kumar and Singh (2023) delves into the challenges faced by Kannada content creators in the OTT space, such as competition from other regional and international content. However, the future looks promising, with increasing digital penetration and changing audience preferences providing opportunities for growth (Kumar & Singh, 2023). 10. OTT Growth and Regional Content Studies on the growth of OTT platforms highlight the increasing demand for regional content. Platforms like Amazon Prime Video [...] Subtitles play a crucial role in breaking language barriers for regional content. Research indicates that more than 60% of viewers for Kannada content on OTT platforms use subtitles, enabling broader accessibility and enhancing viewer engagement (Sharma et al., 2020). 1.5 SCOPE OF THE STUDY This study analyses the most popular Kannada films and series available on OTT platforms to identify the factors contributing to their success. It examines a range of aspects, including narrative structures, genre preferences, cultural resonance, production quality, and marketing strategies. The research aims to uncover insights into the dynamics of Kannada content consumption on digital platforms by understanding audience engagement patterns and the specific elements that attract viewers. The scope',
    'score': 0.5608546},
   {'title': 'Pan-Indian film - Wikipedia',
    'url': 'https://en.wikipedia.org/wiki/Pan-Indian_film',
    'content': '## Notable films considered to be pan-Indian\n\n| Year | Title | Director | Original language(s) | Ref. |\n ---  --- \n| 2015 | Baahubali: The Beginning | S. S. Rajamouli | Telugu |  |\n| 2017 | Baahubali 2: The Conclusion |  |\n| 2018 | 2.0 "2.0 (film)") | S. Shankar | Tamil |  |\n| KGF: Chapter 1 | Prashanth Neel | Kannada |  |\n| 2021 | Pushpa: The Rise | Sukumar | Telugu |  |\n| 2022 | RRR | S. S. Rajamouli |  |\n| KGF: Chapter 2 | Prashanth Neel | Kannada |  |\n| Brahmāstra: Part One – Shiva | Ayan Mukerji | Hindi |  |\n| 2023 | Animal "Animal (2023 Indian film)") | Sandeep Reddy Vanga |  |\n| Salaar: Part 1 – Ceasefire | Prashanth Neel | Telugu |  |\n| 2024 | Kalki 2898 AD | Nag Ashwin |  |\n| Pushpa 2: The Rule | Sukumar |  |\n| 2025 | Kantara: Chapter 1 | Rishab Shetty | Kannada |  | [...] Kannada film KGF: Chapter 1 (2018) directed by Prashanth Neel also released in five languages, thereby becoming the first major Pan-Indian film from Kannada cinema.\n\nFollowing the success of the Telugu films Pushpa: The Rise (2021) and RRR (2022), Rahul Devulapalli of The Week "The Week (Indian magazine)") identified "Content, marketing, [and] indulgent overseas audience" have led to the rise of pan-Indian films from Telugu cinema. [...] A pan-Indian film is typically marketed and released in multiple languages across India, including Telugu, Hindi, Tamil, Malayalam, Kannada and other regional languages. Such films aim to transcend linguistic, demographic, social, regional, ethnic and cultural barriers, seeking to resonate with a wide audience.\n\n## History',
    'score': 0.559411},
   {'title': 'Kannada Cinema: Pan-India dreams challenge local film industry',
    'url': 'https://www.deccanherald.com/india/karnataka/big-budgets-bigger-losses-is-pan-india-ambition-hurting-kannada-cinema-3932186',
    'content': 'Sign in\n\nDH Specials\n\nPolitics\n\nBengaluru\n\nFIFA World Cup\n\nHealth\n\nEducation\n\nTechnology\n\nDH Brandspot\n\nEpaper\n\nSign in\n\nMenu\n\n×\n\nADVERTISEMENT\n\nADVERTISEMENT\n\nHomeindiakarnataka\n\n# Big budgets, bigger losses: Is pan-India ambition hurting Kannada cinema?\n\nWhen filmmakers only templatise the last big hit, they neglect the wealth of intimate cinematic possibilities in their midst\n\nS R Ramakrishna\n\nPranati A S\n\nLast Updated : 15 March 2026, 08:59IST\n\nADVERTISEMENT\n\nJoin Us\n\nPrefer\n\nComments\n\nADVERTISEMENT\n\nPublished 14 March 2026, 21:32IST\n\nKarnataka NewsKannada cinemaSpecialsInSight\n\n## Follow us on :\n\n## Follow Us',
    'score': 0.54942364},
   {'title': 'A Study on Impact of Cinema Industry on Changes in Behavioural and Consumption Patterns of Gen Z in Indian Context',
    'url': 'https://www.abacademies.org/articles/a-study-on-impact-of-cinema-industry-on-changes-in-behavioural-and-consumption-patterns-of-gen-z-in-indian-context-16936.html',
    'content': 'Limitations and Future Scope of Research',
    'score': 0.46964246}],
  'priority': 'HIGH'}] ,
  'user_query' : "Detailed explanation  about Kannada movie"
    })



    print(response['user_query'])
    print(response['evidence'])